### ISSUE TITLE
Menu items do not fit into the view

### ISSUE THREAD

**Issue by reversecoder** [Cleveroad/CycleMenu#4]
Hello,

Thanks for the beautiful library.

I have used CycleMenu into the activity view. I wanted to add 3 items into view. The parent view is a relative layout-

`<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:background="#FFFFFF"
    tools:context="com.cleveroad.cyclemenusample.MainActivity">

    <com.cleveroad.cyclemenuwidget.CycleMenuWidget
        android:id="@+id/cycleMenuView"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:layout_alignParentBottom="true"
        app:cm_autoMaxRadius="180dp"
        app:cm_autoMinRadius="10dp"
        app:cm_corner="right_bottom"
        app:cm_fixedRadius="200dp"
        app:cm_item_background_tint="#6a81fe"
        app:cm_radius_scale_type="auto"
        app:cm_scroll_type="endless" />

</RelativeLayout>`
And Called from activity like thus-

`CycleMenuWidget cycleMenuWidget = (CycleMenuWidget) findViewById(R.id.cycleMenuView);
        cycleMenuWidget.setMenuRes(R.menu.cycle_menu_3);`

Finally getting this result-

![screenshot_20180114-170703](https://user-images.githubusercontent.com/6149036/34915353-5702f16e-f94f-11e7-9557-9609ce7d64a4.png)

I have also tried to add this programmatically, but always goes one item under layout from 3 three items. But in recycler view 3 items fit properly.

![screenshot_20180114-175513](https://user-images.githubusercontent.com/6149036/34915673-7d2b0fde-f954-11e7-8836-025c1020b1d5.png)

Thanks in advance for any workaround without recyclerview.

**Comment by vedprakashwagh** [comment]
You can use the
`cycleMenuWidget.setCurrentItemsAngleOffset(double angle)`
method from the library to tackle your issue, just put suitable angle there.

**Comment by VadimHalimendikCr** [comment]
In version 1.0.2 of the library this was fixed.
