### ISSUE TITLE
More customization

### ISSUE THREAD

**Issue by ExQDev** [Cleveroad/CycleMenu#5]
Please, make it possible to set up circle color, radius and margin.
Here you can see some troubles with colors, sizes and alignment.
I hope to use it as a small corner of message with at least semitransparent background (Using [ChatKit](https://github.com/stfalcon-studio/ChatKit)).

![image](https://user-images.githubusercontent.com/17617393/44951433-a273d000-ae6c-11e8-9f5f-1b034c2da64f.png)

**Comment by VadimHalimendikCr** [comment]
In version 1.0.1 of the library this was implemented.
